version: '3'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-db-network
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=recommendationHub
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-db-network

volumes:
  postgres-data:

networks:
  app-db-network:
    driver: bridge
  back-front-network:
    external: true
  